name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^0.5.12+4
  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.1.0
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

